"""Change volume column in Trades to numeric

Revision ID: fd20578e751f
Revises: 52539c28ce64
Create Date: 2025-05-21 15:02:58.111991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd20578e751f'
down_revision = '52539c28ce64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
